application: blackberry-10
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
  login: required
- url: /static
  static_dir: static
- url: /[0-9]*
  script: _go_app
- url: /mu.*
  script: _go_app
- url: /.*clicks
  script: _go_app
- url: /.*
  script: _go_app
  login: required
